# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  install:
    desc: Install required development environment
    cmds:
      - uv venv
      - uv sync --dev
      - uv run pre-commit install

  run:
    cmds:
      - uv run reflex run

  test:
    cmds:
      - uv run pytest

  jupyter:
    cmds:
      - uv run jupyter lab

  sync:
    desc: Sync from GitHub and install dependencies
    cmds:
      - git fetch
      - git pull
      - uv sync --dev
